config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'pages#home'
  get :hello_world, to: 'pages#hello_world'

  localized do
    get  'newsletter_subscription', to: 'newsletter_subscriptions#new', as: :newsletter_subscription
    post 'newsletter_subscription', to: 'newsletter_subscriptions#create', as: :create_newsletter_subscription
    get  'support_contact', to: 'support_contacts#new', as: :support_contact
    post 'support_contact', to: 'support_contacts#create', as: :create_support_contact
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
# frozen_string_literal: true

class City < ApplicationRecord
  include ChronoModel::TimeMachine

  validates :name, presence: true

  belongs_to :country

  has_many :schools, dependent: :destroy
end

app/models/country.rb
# frozen_string_literal: true

class Country < ApplicationRecord
  include ChronoModel::TimeMachine

  has_many :cities, dependent: :destroy
  has_many :schools, through: :cities
  has_many :students, through: :schools

  validates :name, presence: true
end

app/models/movie.rb
# frozen_string_literal: true

class Movie < ApplicationRecord
  include ChronoModel::TimeMachine

  belongs_to :studio, class_name: 'Movies::Studio'

  def to_s
    name
  end
end

app/models/movies/studio.rb
# frozen_string_literal: true

module Movies
  class Studio < ApplicationRecord
    has_many :movies, inverse_of: :studio
  end
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  include ChronoModel::TimeMachine

  belongs_to :user

  has_many :units

  def to_s
    name
  end
end

app/models/school.rb
# frozen_string_literal: true

class School < ApplicationRecord
  include ChronoModel::TimeMachine

  belongs_to :city
  has_one :country, through: :city

  has_many :students, dependent: :destroy

  validates :name, presence: true
end

app/models/student.rb
# frozen_string_literal: true

class Student < ApplicationRecord
  include ChronoModel::TimeMachine

  belongs_to :school
  has_one :city, through: :school
  has_one :country, through: :city

  validates :name, presence: true
end

app/models/unit.rb
# frozen_string_literal: true

class Unit < ApplicationRecord
  include ChronoModel::TimeMachine

  belongs_to :project

  has_one :user, through: :project

  def to_s
    name
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def page_title(title)
    content_for(:title) { title.to_s }
  end

  def page_meta_description(meta_description)
    content_for(:meta_description) { meta_description.to_s }
  end

  def yield_or_default(section, default = '')
    content_for?(section) ? content_for(section) : default
  end
end

app/views/layouts/application.html.slim
doctype html
html lang=I18n.locale data-default-lang=I18n.default_locale
  head
    title = yield_or_default :title, action_name.titlecase

    / Required meta tags
    meta charset='utf-8'
    meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'
    meta name='description' content=yield(:meta_description)

    = csrf_meta_tags
    = csp_meta_tag
    = yield :head

    = stylesheet_pack_tag 'application', media: 'all', 'data-turbo-track': 'reload'

    / Web App manifest
    link href='/manifest.json' rel='manifest'
    meta content=t('app_name') name='Rails 6 Starter App'
    meta content='#e00000' name='theme-color'

    link href='launcher-icon-180.png' rel='apple-touch-icon' sizes='180x180'

    / Placed at the top of the document because of Turbo
    = javascript_pack_tag 'application', 'data-turbo-track': 'reload'

  body
    == render 'shared/navbar'

    .main-container.container = yield

    == render 'shared/footer'

app/views/pages/hello_world.html.slim
- page_title 'Hello World'

h1.mt-3
  = yield :title

app/views/pages/home.html.slim
- page_title t('app_name')
- page_meta_description t('meta_description')

h1.mt-3
  = yield :title
  small< 3.0.0
ul.list-inline.lead
  li.list-inline-item
    | Ruby
    small.text-body-secondary< 3.1.7
  li.list-inline-item
    | Rails
    small.text-body-secondary< 6.1.7.10
  li.list-inline-item
    | Bootstrap
    small.text-body-secondary< 5.3.8
  li.list-inline-item
    | Font Awesome (SVG)
    small.text-body-secondary< 7.1.0

app/views/shared/_footer.html.slim
footer.main-footer
  .container
    hr
    p
      = link_to 'https://github.com/diowa/ruby3-rails6-bootstrap-heroku' do
        span.fab.fa-github> aria-hidden='true'
        span.visually-hidden GitHub
        | diowa/ruby3-rails6-bootstrap-heroku

app/views/shared/_navbar.html.slim
nav.main-navbar.navbar.main-navbar.bg-body-tertiary.navbar-expand-lg
  .container
    = link_to t('app_name'), root_path, class: 'navbar-brand'
    button.navbar-toggler type='button' data-bs-toggle='collapse' data-bs-target='#main-navbar-collapse' aria-controls='main-navbar-collapse' aria-expanded='false' aria-label=t('.toggle_navigation')
      span.navbar-toggler-icon
    #main-navbar-collapse.collapse.navbar-collapse
      ul.navbar-nav.main-navbar-nav.ml-auto
        li.nav-item = link_to 'Hello World', hello_world_path, class: 'nav-link'